name: Continuous Deployment with Docker Container

on: [push]

jobs:
  deploy:
    name: Docker Deployment
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Run 
      env:
        SERVICE_NAME: 54-180-128-102
        IMAGE_NAME: raccoony/lightsail-nginx:${{ github.sha }}
      run: |
        echo $IMAGE_NAME:$IMAGE_TAG
        docker build -t $IMAGE_NAME .
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push $IMAGE_NAME
        envsubst deployment.yaml
        aws lightsail create-container-service-deployment --service-name $SERVICE_NAME --cli-input-yaml file://deployment.yaml